# Generated by Django 4.2.5 on 2023-10-25 00:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut', models.CharField(max_length=10, unique=True, verbose_name='rut')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaProductos',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Productos',
                'ordering': ['nombre_categoria'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaProyecto',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoría de Proyecto',
                'verbose_name_plural': 'Categorias de Proyectos',
                'ordering': ['nombre_categoria'],
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('rut_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cotizaciones',
            fields=[
                ('id_cotizacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cotizacion', models.DateField(default=datetime.datetime.now)),
                ('nombre_cotizacion', models.CharField(blank=True, max_length=100, null=True)),
                ('subtotal', models.FloatField(default=0)),
                ('iva', models.IntegerField(default=19)),
                ('total', models.FloatField(default=0)),
                ('comentario', models.TextField(blank=True, max_length=1000, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clientes')),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['id_cotizacion'],
            },
        ),
        migrations.CreateModel(
            name='MarcaProductos',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Marca de Producto',
                'verbose_name_plural': 'Marcas de Productos',
                'ordering': ['nombre_marca'],
            },
        ),
        migrations.CreateModel(
            name='StatusProyecto',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_status', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Status de Proyecto',
                'verbose_name_plural': 'Status de Proyectos',
                'ordering': ['nombre_status'],
            },
        ),
        migrations.CreateModel(
            name='SubcategoriaProductos',
            fields=[
                ('id_subcategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_subcategoria', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Subcategoría de Producto',
                'verbose_name_plural': 'Subcategorías de Productos',
                'ordering': ['nombre_subcategoria'],
            },
        ),
        migrations.CreateModel(
            name='VarianteProductos',
            fields=[
                ('id_variante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_variante', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Productos',
                'ordering': ['nombre_variante'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(max_length=100)),
                ('instalacion', models.BooleanField(default=False)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('plazo_entrega', models.DateField()),
                ('categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.categoriaproyecto')),
                ('cliente', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clientes')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.statusproyecto')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['id_proyecto'],
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_compra', models.FloatField(default=0)),
                ('precio_venta', models.FloatField(default=0)),
                ('categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.categoriaproductos')),
                ('marca', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.marcaproductos')),
                ('subcategoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.subcategoriaproductos')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.varianteproductos')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id_producto'],
            },
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(max_length=100)),
                ('proyecto_id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proyecto')),
                ('trabajadores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['nombre_equipo'],
            },
        ),
        migrations.CreateModel(
            name='EquipoAsignacion',
            fields=[
                ('asignacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField(default=datetime.datetime.now)),
                ('fecha_termino', models.DateField()),
                ('tarea', models.CharField(max_length=100)),
                ('equipo_id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipos')),
                ('proyecto_id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proyecto')),
            ],
            options={
                'verbose_name': 'Tarea de Equipo',
                'verbose_name_plural': 'Tareas de Equipos',
                'ordering': ['fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizaciones',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.FloatField(default=0)),
                ('id_cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cotizaciones')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productos')),
            ],
            options={
                'verbose_name': 'Detalle de Cotización',
                'verbose_name_plural': 'Detalles de Cotizaciones',
                'ordering': ['id_cotizacion'],
            },
        ),
        migrations.CreateModel(
            name='Avances',
            fields=[
                ('avance_id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='avances')),
                ('comentario', models.CharField(max_length=100)),
                ('asignacion_asignacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.equipoasignacion')),
                ('equipo_id_equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.equipos')),
                ('proyecto_id_proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.proyecto')),
            ],
            options={
                'verbose_name': 'Avance',
                'verbose_name_plural': 'Avances',
                'ordering': ['avance_id'],
            },
        ),
    ]
