# Generated by Django 4.2.5 on 2023-10-05 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut', models.CharField(max_length=10, unique=True, verbose_name='rut')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaProyecto',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('rut_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id_equipo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(max_length=100)),
                ('instalacion', models.BooleanField(default=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('plazo_entrega', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriaproyecto')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clientes')),
                ('equipo', models.ManyToManyField(to='core.equipos')),
            ],
        ),
        migrations.CreateModel(
            name='StatusProyecto',
            fields=[
                ('id_status', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatusPorProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observacion', models.CharField(max_length=100)),
                ('proyecto_id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proyecto')),
                ('status_id_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.statusproyecto')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.statusproyecto'),
        ),
        migrations.AddField(
            model_name='equipos',
            name='proyecto_id_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proyecto'),
        ),
        migrations.AddField(
            model_name='equipos',
            name='trabajadores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EquipoAsignacion',
            fields=[
                ('asignacion_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tiempo_asignado', models.DateField()),
                ('tiempo_final', models.DateField()),
                ('equipo_id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipos')),
                ('proyecto_id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Avances',
            fields=[
                ('avance_id', models.IntegerField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='avances')),
                ('comentario', models.CharField(max_length=45)),
                ('asignacion_asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipoasignacion')),
                ('equipo_id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipos')),
                ('equipo_proyectos_id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proyecto')),
            ],
        ),
    ]
