# Generated by Django 4.2.5 on 2023-11-18 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statustarea',
            old_name='id_status',
            new_name='id_status_tarea',
        ),
    ]
