# Generated by Django 4.2.5 on 2023-10-05 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='equipo',
            field=models.ManyToManyField(null=True, to='core.equipos'),
        ),
    ]
