# Generated by Django 4.2.5 on 2023-11-18 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_id_status_statustarea_id_status_tarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusproyecto',
            old_name='id_status',
            new_name='id_status_p',
        ),
    ]
