# Generated by Django 4.2.5 on 2023-10-01 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoriaproyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.categoriaproyecto'),
        ),
    ]
