# Generated by Django 4.2.5 on 2023-10-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_proyecto_equipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='equipo',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='equipo',
            field=models.CharField(blank='true', max_length=100, null='true', verbose_name='Equipos'),
            preserve_default='true',
        ),
    ]
