# Generated by Django 4.2.5 on 2023-10-01 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_proyecto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusProyecto',
            fields=[
                ('id_status', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.statusproyecto'),
        ),
    ]
