# Generated by Django 4.2.5 on 2023-11-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_id_status_statusproyecto_id_status_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=60),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=60),
        ),
    ]
