# Generated by Django 4.2.5 on 2023-10-05 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_proyecto_equipo_proyecto_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='equipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.equipos'),
        ),
    ]
