# Generated by Django 4.2.5 on 2023-11-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_productos_precio_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precio_compra',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=60),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio_venta',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=60),
        ),
    ]
