# Generated by Django 4.2.5 on 2023-11-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cotizaciones_iva_alter_cotizaciones_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecotizaciones',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
