# Generated by Django 4.2.5 on 2023-11-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_productos_precio_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precio_compra',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio_venta',
            field=models.FloatField(default=0),
        ),
    ]
