# Generated by Django 4.2.5 on 2023-11-22 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_productos_precio_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rut',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Este campo solo puede contener digitos.', regex='^[0-9kK]+$')], verbose_name='rut'),
        ),
    ]
