# Generated by Django 4.2.5 on 2023-11-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cotizaciones_iva_alter_cotizaciones_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizaciones',
            name='iva',
            field=models.DecimalField(decimal_places=1, default=19, max_digits=9),
        ),
        migrations.AlterField(
            model_name='cotizaciones',
            name='subtotal',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='cotizaciones',
            name='total',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=9),
        ),
    ]
