# Generated by Django 4.2.5 on 2023-10-05 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_proyecto_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avances',
            name='equipo_proyectos_id_proyecto',
        ),
    ]
