# Generated by Django 4.2.5 on 2023-10-05 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_avances_equipo_proyectos_id_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='avances',
            name='equipo_proyectos_id_proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.proyecto'),
            preserve_default=False,
        ),
    ]
