# Generated by Django 4.2.5 on 2023-10-05 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_avances_equipo_proyectos_id_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.statusproyecto'),
        ),
        migrations.DeleteModel(
            name='StatusPorProyecto',
        ),
    ]
