# Generated by Django 4.2.5 on 2023-11-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_cotizaciones_iva_alter_cotizaciones_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precio_compra',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio_venta',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
    ]
