# Generated by Django 4.2.5 on 2023-11-04 17:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_cotizaciones_iva_alter_cotizaciones_subtotal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('asignacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField(default=datetime.datetime.now)),
                ('fecha_termino', models.DateField()),
                ('tarea', models.CharField(max_length=100)),
                ('equipo_id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipos')),
            ],
            options={
                'verbose_name': 'Tarea de Equipo',
                'verbose_name_plural': 'Tareas de Equipos',
                'ordering': ['fecha_asignacion'],
            },
        ),
        migrations.RemoveField(
            model_name='avances',
            name='asignacion_asignacion',
        ),
        migrations.DeleteModel(
            name='EquipoAsignacion',
        ),
        migrations.AddField(
            model_name='avances',
            name='tarea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tareas'),
            preserve_default=False,
        ),
    ]
