# Generated by Django 4.2.5 on 2023-11-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_proyecto_id_cotizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusCotizacion',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_status', models.CharField(max_length=100)),
            ],
        ),
    ]
