# Generated by Django 4.2.5 on 2023-10-05 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_proyecto_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avances',
            old_name='equipo_proyectos_id_proyecto',
            new_name='proyecto_id_proyecto',
        ),
    ]
