# Generated by Django 4.2.5 on 2023-11-27 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cotizaciones_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='id_cotizacion',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='core.cotizaciones'),
            preserve_default=False,
        ),
    ]
