# Generated by Django 4.2.5 on 2023-10-05 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_equipo_proyectos_id_proyecto_avances_proyecto_id_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProductos',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cotizaciones',
            fields=[
                ('id_cotizacion', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_cotizacion', models.DateField()),
                ('nombre_cotizacion', models.CharField(max_length=100)),
                ('total_neto', models.IntegerField()),
                ('total_impuestos', models.IntegerField()),
                ('total', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='MarcaProductos',
            fields=[
                ('id_marca', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubcategoriaProductos',
            fields=[
                ('id_subcategoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_subcategoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VarianteProductos',
            fields=[
                ('id_variante', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_variante', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio_compra', models.IntegerField()),
                ('precio_venta', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriaproductos')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.marcaproductos')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subcategoriaproductos')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.varianteproductos')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCotizaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('id_cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cotizaciones')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productos')),
            ],
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.detallecotizaciones'),
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='generado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
