# Generated by Django 4.2.5 on 2023-11-27 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_proyecto_id_cotizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizaciones',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.statuscotizacion'),
            preserve_default=False,
        ),
    ]
