# Generated by Django 4.2.5 on 2023-10-16 16:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_cotizaciones_detalle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avances',
            name='asignacion_asignacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.equipoasignacion'),
        ),
        migrations.AlterField(
            model_name='avances',
            name='equipo_id_equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.equipos'),
        ),
        migrations.AlterField(
            model_name='avances',
            name='proyecto_id_proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
