# Generated by Django 4.2.5 on 2023-11-27 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_cotizaciones_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizaciones',
            old_name='estado',
            new_name='status',
        ),
    ]
