# Generated by Django 4.2.5 on 2023-10-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_avances_asignacion_asignacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipoasignacion',
            name='tarea',
            field=models.CharField(default='picar madera', max_length=100),
            preserve_default=False,
        ),
    ]
