# Generated by Django 4.2.5 on 2023-11-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_detalleequipo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='equipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
