# Generated by Django 4.2.7 on 2024-02-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=60),
        ),
    ]
