# Generated by Django 4.2.5 on 2023-11-04 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_equipos_equipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipos',
            name='equipo',
        ),
    ]
