# Generated by Django 4.2.5 on 2023-11-04 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_equipos_equipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleequipo',
            options={'ordering': ['id_equipo'], 'verbose_name': 'Detalle de Equipo', 'verbose_name_plural': 'Detalle de Equipos'},
        ),
        migrations.RenameField(
            model_name='detalleequipo',
            old_name='equipo_id_equipo',
            new_name='id_equipo',
        ),
    ]
