# Generated by Django 4.2.7 on 2024-02-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_cotizaciones_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizaciones',
            name='descuento',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=60),
        ),
        migrations.AlterField(
            model_name='cotizaciones',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=60),
        ),
    ]
