# Generated by Django 4.2.7 on 2024-02-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_cotizaciones_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizaciones',
            name='iva',
            field=models.DecimalField(decimal_places=0, default=19, max_digits=60),
        ),
        migrations.AlterField(
            model_name='cotizaciones',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=60),
        ),
    ]
