# Generated by Django 4.2.7 on 2024-03-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_cotizaciones_iva_alter_cotizaciones_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='correo',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
