# Generated by Django 4.2.5 on 2023-11-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_asignacion_id_tareas_tarea_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='tarea',
            field=models.TextField(max_length=100),
        ),
    ]
