# Generated by Django 4.2.7 on 2024-03-23 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_clientes_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizaciones',
            name='generado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
