# Generated by Django 4.2.5 on 2023-11-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_productos_stock_alter_tareas_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='id_producto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
