# Generated by Django 4.2.7 on 2024-03-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_cotizaciones_generado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id_formapago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_formapago', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='abono',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
