# Generated by Django 4.2.5 on 2023-11-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_avances_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avances',
            name='comentario',
            field=models.TextField(max_length=100),
        ),
    ]
