# Generated by Django 4.2.7 on 2024-03-23 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_formapago_cotizaciones_abono'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='formapago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.formapago'),
        ),
    ]
