# Generated by Django 4.2.5 on 2023-11-11 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_avances_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avances',
            name='equipo_id_equipo',
        ),
        migrations.RemoveField(
            model_name='avances',
            name='proyecto_id_proyecto',
        ),
    ]
