# Generated by Django 4.2.7 on 2024-03-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_cotizaciones_formapago'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='comuna',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
