# Generated by Django 4.2.5 on 2023-11-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_avances_equipo_id_equipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varianteproductos',
            name='id_variante',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='varianteproductos',
            name='nombre_variante',
            field=models.CharField(default='Sin Variante', max_length=100),
        ),
    ]
