# Generated by Django 4.2.5 on 2023-11-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_varianteproductos_id_variante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='variante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='VarianteProductos',
        ),
    ]
