# Generated by Django 4.2.7 on 2024-07-16 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_proyecto_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedidas',
            fields=[
                ('id_unidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_unidad', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='productos',
            name='unidad_medida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.unidadmedidas'),
        ),
    ]
